### ISSUE TITLE
Support `--list` function

### ISSUE THREAD

**Issue by teymour-aldridge** [softdevteam/lang_tester#103]
I use [nextest](https://nexte.st/) to test the programs in my project. I would like to integrate this with `lang_tester` (which I also use), however, this is currently not possible because `lang_tester` doesn't support [all of the features `nextest` requires](https://nexte.st/book/custom-test-harnesses.html#manually-implementing-a-test-harness).

It would be wonderful if these could be implemented (I would be happy to do this).

**Comment by ltratt** [comment]
AIUI these changes wouldn't effect anyone not using `nextest` (and, also, wouldn't require us adding `nextest` as a dependency -- it doesn't compile on my OS!)? Assuming that's correct, I would welcome a PR which does this!

**Comment by ltratt** [comment]
Timing out.
