### ISSUE TITLE
PR #30 causes tests to never end on macOS.

### ISSUE THREAD

**Issue by ummarikar** [softdevteam/lang_tester#46]
After testing this repository with https://github.com/softdevteam/yksom, I have found that #30, specifically [`#a8f8044`](https://github.com/softdevteam/lang_tester/pull/30/commits/a8f80443f0ec2bf983aa22ee479d725e91459488), has caused running `cargo test` to never end on macOS (tested on two Macs):
<img width="554" alt="Screenshot 2019-11-27 at 17 38 32" src="https://user-images.githubusercontent.com/32270615/69919910-e0014780-1479-11ea-9c93-c5f1b465eaec.png">

**Comment by ltratt** [comment]
Can you propose a fix (preferably raising a PR to fix it)? I suspect that searching for "OS X and poll" might be a fruitful place to start!

**Comment by ltratt** [comment]
This *might* be relevant but I'm not sure https://www.greenend.org.uk/rjk/tech/poll.html

**Comment by ummarikar** [comment]
I'll see what I can do :)

**Comment by ummarikar** [comment]
UPDATE: the poll command on OSX works. I found this out by running the C code at this link - https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/.  https://github.com/softdevteam/lang_tester/blob/a1f51ec8b747cb252a0b8df4846ff43c8c0c6c8b/src/tester.rs#L729-L731
This if statement is never entered (on OSX) as the condition is always false. Each side of the conjunction is always false whereas this if statement is always executed on Linux. I believe this is what is causing the loop.

**Comment by ummarikar** [comment]
I found that the difference between Linux and MacOS using filedescriptor `poll` is the following:
```The filedescriptor crate offers a poll(2) compatible interface suitable for testing the readiness of a set of file descriptors. On unix systems this is a very thin wrapper around poll(2), except on macOS where it is actually a wrapper around the select(2) interface.```
Maybe this is relevant? Not too sure just speculating at the moment.

**Comment by ummarikar** [comment]
> UPDATE: the poll command on OSX works. I found this out by running the C code at this link - https://daniel.haxx.se/blog/2016/10/11/poll-on-mac-10-12-is-broken/.
> 
> https://github.com/softdevteam/lang_tester/blob/a1f51ec8b747cb252a0b8df4846ff43c8c0c6c8b/src/tester.rs#L729-L731
> 
> 
> This if statement is never entered (on OSX) as the condition is always false. Each side of the conjunction is always false whereas this if statement is always executed on Linux. I believe this is what is causing the loop. Trying to figure out why this behaviour is the case...

I believe I have found the issue. Because `filedescriptor` uses `select(2)`, there is no implementation for `POLLHUP`, as such, the if statement mentioned above won't enter on macOS. You can see this in the `filedescriptor` code below:

https://github.com/wez/wzsh/blob/d23690608ad2303bc03b53901babddabb3c308ba/filedescriptor/src/unix.rs#L408-L464

**Comment by ltratt** [comment]
OK, so you might want to a) try patching `filedescriptor` locally to fix the problem (you can temporarily adjust `lang_tester`'s `Cargo.toml` to point to your local copy) b) if that works file a PR against `filedescriptor`.

**Comment by ummarikar** [comment]
The maintainer of `filedescriptor` could not accept my PR but kindly gave us a fix that I am looking into now. For reference see - https://github.com/wez/wzsh/pull/1.

**Comment by ltratt** [comment]
Ouch, one very good point mentioned therein is that the file descriptors should be non-blocking. Not doing so was a mistake on my part, and we should definitely make them non-blocking.

**Comment by ummarikar** [comment]
Created a fix based on what was provided but still getting the same issue on macOS. I'll have to test it to see if it works on the Linux machines in the labs tomorrow but it's looking like poll is not a good solution for mac.

**Comment by ltratt** [comment]
There's no point trying it on Linux if it doesn't work on OS X.

**Comment by ummarikar** [comment]
Closing this issue as #51 has fixed the problems on OS X.
