### ISSUE TITLE
Print the expected vs the actual output for failing tests

### ISSUE THREAD

**Issue by antoyo** [softdevteam/lang_tester#59]
Hi.
It seems the tester only prints the expected output, not the actual output.
Would it be possible to print both?
Also, I think `eprintln!()` does not lock `stderr`, so the printed text of the different tests can be mixed up.
Thanks to fix these issues.

**Comment by ltratt** [comment]
> It seems the tester only prints the expected output, not the actual output.

It should (assuming there are no bugs) print the actual stderr/stdout output only when they different from the expected output. I admit that this can sometimes be surprising, and I'm open to suggestions of how to make it clearer to users as to what's going on. One possibility is to add a switch that says "always print stderr/stdout even if they're correct".

> Also, I think eprintln!() does not lock stderr, so the printed text of the different tests can be mixed up.

I'm not quite sure what this means. Can you give an example of something incorrect happening?

**Comment by antoyo** [comment]
Oh, you're right: there was a small typo in my expected output, so I thought it was showing it instead of the actual output.
It would be better to show both (instead of just the actual output) and on separate lines (to make them easier to diff). Something like this:
```
Actual stdout:   Actual
Expected stdout: Expected
```

For the incorrect output, here's what my output looks like:
```
test lang_tests::empty_main ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 3"

test lang_tests::static ... ok
test lang_tests::slice ... ok" Compiler:\n\n Run-time:\n   status: signal"
" Compiler:\n\n Run-time:\n   stdout: 2\n     7\n     6\n     11"

test lang_tests::tuple ... ok" Compiler:\n\n Run-time:\n   status: 2"

test lang_tests::mut_ref ... ok" Compiler:\n\n Run-time:\n   stdout: 41\n     39\n     10"

test lang_tests::exit ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 1\n     2"

test lang_tests::int_overflow ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 42\n     7\n     5"

test lang_tests::operations ... ok" Compiler:\n\n Run-time:\n   stdout: 2\n     7 8\n     10"

test lang_tests::structs ... ok" Compiler:\n\n Run-time:\n   status: signal"

test lang_tests::abort1 ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: Arg: 1\n     Argument: 1"

test lang_tests::array ... ok" Compiler:\n\n Run-time:\n   status: 1"

test lang_tests::assign ... ok
test lang_tests::closure ... ok
test lang_tests::exit_code ... ok
test lang_tests::abort2 ... okoktest test ... ok
```
There are sometimes two newlines in a row, sometimes a newline is missing.
Also, the stdout `Arg: 1\n     Argument: 1` is for the test `closure`, yet it is shown on the same line as `abort1`.

My guess is that the tests are run in parallel and the `eprintln!` macro does not lock.
If that is the case, [the `lock()` method](https://doc.rust-lang.org/stable/std/io/struct.Stderr.html#method.lock) should be used.

**Comment by ltratt** [comment]
How are you running the tests? Are you using `--nocapture`?

**Comment by antoyo** [comment]
Just `cargo test`.

**Comment by ltratt** [comment]
That's weird: with plain `cargo test` it shouldn't be printing anything out until all the tests have completed. Do you have an example repo or similar?

**Comment by antoyo** [comment]
I'll see if I can upload an example somewhere.

Also, I can confirm the locking stderr improves the printing.
Without `lock()`:
```
test lang_tests::static ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 3"

test lang_tests::slice ... ok" Compiler:\n\n Run-time:\n   status: signal"

test lang_tests::empty_main ... ok" Compiler:\n\n Run-time:\n   stdout: 2\n     7\n     6\n     11"

test lang_tests::tuple ... ok" Compiler:\n\n Run-time:\n   status: 2"

test lang_tests::mut_ref ... ok" Compiler:\n\n Run-time:\n   stdout: 41\n     39\n     10"

test lang_tests::exit ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 1\n     2"

test lang_tests::operations ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 42\n     7\n     5"

test lang_tests::structs ... ok" Compiler:\n\n Run-time:\n   stdout: 2\n     7 8\n     10"

test lang_tests::int_overflow ... ok" Compiler:\n\n Run-time:\n   status: signal"

test lang_tests::abort1 ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: Arg: 1\n     Argument: 1"

test lang_tests::array ... ok" Compiler:\n\n Run-time:\n   status: 1"

test lang_tests::assign ... ok
test lang_tests::exit_code ... ok
test lang_tests::closure ... ok
test lang_tests::abort2 ... okoktest test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
With `lock()`:
```
test lang_tests::empty_main.rs ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 3"

test lang_tests::static.rs ... ok" Compiler:\n\n Run-time:\n   status: signal"

test lang_tests::slice.rs ... ok" Compiler:\n\n Run-time:\n   stdout: 2\n     7\n     6\n     11"

test lang_tests::tuple.rs ... ok" Compiler:\n\n Run-time:\n   status: 2"

test lang_tests::mut_ref.rs ... ok" Compiler:\n\n Run-time:\n   stdout: 41\n     39\n     10"

test lang_tests::exit.rs ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 1\n     2"

test lang_tests::structs.rs ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: 42\n     7\n     5"

test lang_tests::int_overflow.rs ... ok" Compiler:\n\n Run-time:\n   stdout: 2\n     7 8\n     10"

test lang_tests::operations.rs ... ok" Compiler:\n\n Run-time:\n   status: signal"

test lang_tests::abort1.rs ... ok" Compiler:\n\n Run-time:\n   status: 0\n   stdout: Arg: 1\n     Argument: 1"

test lang_tests::assign.rs ... ok" Compiler:\n\n Run-time:\n   status: 1"

test lang_tests::array.rs ... ok
test lang_tests::closure.rs ... ok
test lang_tests::exit_code.rs ... ok
test lang_tests::abort2.rs ... ok

test result: ok. 15 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

test test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
The `stdout` is still associated with the wrong test. Let me check if I can see why.

**Comment by ltratt** [comment]
Something seems to have gone wrong in lang_tester, but I'll really need an example to work out what.

**Comment by antoyo** [comment]
Ok, I'll make one.

By the way, are you on a Mac?
Because I think the tests do not run in parallel on Mac.

**Comment by ltratt** [comment]
I test on OpenBSD and Linux. There shouldn't be anything which stops tests running in parallel on a Mac AFAIK.

**Comment by antoyo** [comment]
You're right, I was confusing with another problem for tests on Mac.

[Here it is.](https://github.com/antoyo/test_lang_tester)

Here's the output for `cargo test`:
```
running 1 test
" Compiler:\n\n Run-time:\n   status: signal"
" Compiler:\n\n Run-time:\n   status: 2"
" Compiler:\n\n Run-time:\n   status: 0"
" Compiler:\n\n Run-time:\n   status: signal"

test lang_tests::empty_mail ... ok" Compiler:\n\n Run-time:\n   status: 1"

test lang_tests::exit ... ok
test lang_tests::exit_code ... ok
test lang_tests::abort2 ... ok
test lang_tests::abort ... okoktest test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
Here's the output for `cargo test -- --test-threads=1`:
```
running 1 test
test test ... 
test lang_test::exit ... " Compiler:\n\n Run-time:\n   status: 2"
ok
test lang_test::abort2 ... " Compiler:\n\n Run-time:\n   status: signal"
ok
test lang_test::empty_mail ... " Compiler:\n\n Run-time:\n   status: 0"
ok
test lang_test::abort ... " Compiler:\n\n Run-time:\n   status: signal"
ok
test lang_test::exit_code ... " Compiler:\n\n Run-time:\n   status: 1"
okokok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
(This is closer to what I would expect.)

**Comment by ltratt** [comment]
It still shouldn't be printing those things out, so it would be very helpful to see the repo that's causing this.

**Comment by antoyo** [comment]
It's linked in the previous message.
Here it is again: https://github.com/antoyo/test_lang_tester

**Comment by ltratt** [comment]
I think the main problem is in `tests/lib.rs` at line 20:

```
            println!("{:?}", lines);
```

When I remove that, most of the incorrect output disappears.

There is then the oddity that the output looks like:

```
$ cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.08s
     Running target/debug/deps/test_lang_tester-a03663f78f8c29c2

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/lib-83b23aea4a0f0086

running 1 test

test lang_tests::abort ... FAILED
test lang_tests::abort2 ... FAILED
test lang_tests::empty_mail ... FAILED
test lang_tests::exit ... FAILED
test lang_tests::exit_code ... FAILEDFAILEDerror: test failed, to rerun pass '--test lib'
```

which is because the test in `tests/lib.rs` is marked as `#[test]` so the test that runs tests fails. I recommend running lang_tests as a `main` method. One way of linking that naturally into `cargo test` can be seen in https://github.com/softdevteam/yksom/blob/master/Cargo.toml#L16.

Hope that helps!

**Comment by antoyo** [comment]
Ok, thanks. It indeed fix the issue.

Any reason why it was done this way?

**Comment by ltratt** [comment]
> Any reason why it was done this way?

Which "it"?

**Comment by antoyo** [comment]
I mean, using a `main` instead of normal test functions?

**Comment by ltratt** [comment]
Yes, because otherwise you get the problem you see: you're trying to map 1 Rust `#[test]` to multiple lang tests and that doesn't really work very well.

**Comment by antoyo** [comment]
Ok, thanks.
