### ISSUE TITLE
Doesn't compile on Windows

### ISSUE THREAD

**Issue by Kixiron** [softdevteam/lang_tester#61]
Due to the usages of `libc` `lang_tester` doesn't compile on Windows, and it'd be great to be able to test on any platform

**Comment by ltratt** [comment]
I'd be happy to take a PR to make it work on Windows, but I'm afraid I don't have such a machine myself. Sorry!

**Comment by Kixiron** [comment]
From poking around a little bit it seems like [this portion](https://github.com/softdevteam/lang_tester/blob/master/src/tester.rs#L672) is the only part that actually uses libc, but I think it should be possible (if easier) to do that timeout-type logic with the std alone, no additional dependencies required

**Comment by ltratt** [comment]
I'd be happy to take a PR which makes that change. I'm afraid I won't be able to find time to do it myself, as our team doesn't have access to a Windows machine to test development on.

**Comment by ltratt** [comment]
Although I'd love to see this fixed, it'll only happen if a Windows-using volunteer takes it on. So this is really just hoping for a PR to arrive! Closing, because unfortunately nothing will happen until someone (not me) raises that PR.
