### ISSUE TITLE
Multi-line stdin

### ISSUE THREAD

**Issue by ltratt** [softdevteam/lang_tester#65]
What should the following do?

```
VM:
  stdin: x
```

It seems fairly clear to me that it should pass the string `x` to the command. Notice that we've stripped the space character between `:` and `x`.

What should we do with multi-line stdin definitions such as:

```
VM:
  stdin:
    x
    y
```

At the moment we would pass the string `x\ny` to the command i.e. we strip the whitespace before `y` too. I believe that's the least-surprising thing to do, but we should consider this before we make a release and start to rely on one behaviour over another.

Thoughts @vext01?

**Comment by vext01** [comment]
I may not be the best person to ask, having never used lang tester, but here goes.

> Notice that we've stripped the space character between : and x

I see a space still.

> At the moment we would pass the string x\ny

So is this about whether or not to strip the indentation?

**Comment by ltratt** [comment]
> So is this about whether or not to strip the indentation?

In essence, yes.

**Comment by vext01** [comment]
We could do [as Rust does](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=152406667bc97d2bace4e373c26bcb64)? i.e. you can have either behaviour depending on if you use `\` or not.

**Comment by ltratt** [comment]
Interesting idea. I might need to chew on this for a bit.
