### ISSUE TITLE
Support out-of-file stdout / stderr output.

### ISSUE THREAD

**Issue by xldenis** [softdevteam/lang_tester#76]
The current API for `test_extract` requires the `stdout/stderr` output to be stored in the test file. This is rather inconvenient if we wish to update these outputs programatically. Instead what is commonly done (for example in `compiletest`) is to store the outputs in `*.stdout` and `*.stderr` files alongside the test cases. 

Would you be open to a secondary (or replacement) API which enables this convention? 

One possible API could be:

```
fn test_extract_path(extractor: Option<Box<dyn Fn(&Path) -> Tests + Send + Sync>>)
```

of course `test_extract` could be expressed as a wrapper around `test_extract_path`. 

Test case regeneration could either be provided by `lang_tester` directly when `test_extract_path` is set, or by test authors overwriting files manually in their tests. If `lang_tester` provides this then `Tests` should store the expectation `Path`s rather than the file contents.

**Comment by ltratt** [comment]
I'm potentially open to this but we'd need to find a non-annoying way of doing so. Two problems jump out at me:

1. Ideally, we don't want to allow people to express both `test_extract` and `test_extract_path`. That suggests collapsing them into one function but ...
2. We don't really want to muck around with requiring say an `enum` for different test options.

I'm not immediately sure how to resolve this quandary but I'll have a think.

**Comment by xldenis** [comment]
> I'm potentially open to this but we'd need to find a non-annoying way of doing so. Two problems jump out at me:
> 
>     1. Ideally, we don't want to allow people to express both `test_extract` and `test_extract_path`. That suggests collapsing them into one function but ...

I think that `test_extract` could be a wrapper around `test_extract_path` that performs a file read and passes that to the closure. The regeneration of output files could be a flag that is set as off in `test_extract`. 
> 
>     2. We don't really want to muck around with requiring say an `enum` for different test options.

Why not? It's certainly better than passing a string in.
> 
> 
> I'm not immediately sure how to resolve this quandary but I'll have a think.

**Comment by ltratt** [comment]
Having played around with this, I think `test_extract` should simply take a `&Path`. Please have a look at https://github.com/softdevteam/lang_tester/pull/77 and see what you think -- comments are welcome!
